version: '3.8'

services:
  pharmcost-app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - pharmcost-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=pharmcost
      - POSTGRES_USER=pharmcost_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - pharmcost-network

volumes:
  postgres_data:

networks:
  pharmcost-network:
    driver: bridge