services:
  - type: web
    name: pharmcost-pro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/vendors
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"